refactor(test): remove tap from expirables
Cadienvan/expirables pull request #40
Opened 2023-12-23 09:47 UTC by mateonunez

As mentioned in https://github.com/Cadienvan/expirables/pull/36 tap is changing a lot of things and license too. I decided to migrate the whole test code base from tap to Node Test Runner using the current `ts-node/esm` loader.

I kept also the c8 for the coverage

2023-12-23 09:58 UTC, Cadienvan approved these changes
Awesome, as always my friend!

2023-12-23 10:01 UTC, Cadienvan requested changes
I tried to run tests but it shows 0 tests

2023-12-23 10:21 UTC, mateonunez commented
Temporary removed Node 20 from the CI, please don't merge @Cadienvan 🙏

2023-12-27 09:34 UTC, Cadienvan approved these changes

2023-12-27 09:34 UTC, merged